import Image from "next/image";
import Fan from "@/components/Fan";
import { Inter } from "next/font/google";

const Home = () => {
	const fans = [
		{
			itemCode: 659,
			brand: "Decor",
			fanName: "Petit Star White",
			material: "Metal And Wood",
			bladeCount: "6",
			bladeMaterial: "Plywood",
			bladeSpan: "77cm",
			reversableBlades: "No",
			controlMethod: "Pull Switch",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "1 x 60W e27",
			recommendedGlobe: "Golfball",
			speed: "3 Speed",
			motorWattage: "55W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/659-400x400.jpg",
		},
		{
			itemCode: 660,
			brand: "Decor",
			fanName: "Petit Star Matt Aluminium",
			material: "Aluminium and MBF wood",
			bladeCount: "6",
			bladeMaterial: "Plywood",
			bladeSpan: "77cm",
			reversableBlades: "No",
			controlMethod: "Pull Switch",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "1 x 60W e27",
			recommendedGlobe: "Golfball",
			speed: "3 Speed",
			motorWattage: "55W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/660-400x400.jpg",
		},
		{
			itemCode: 661,
			brand: "Decor",
			fanName: "Industrial Fan",
			material: "Steel",
			bladeCount: "3",
			bladeMaterial: "Steel",
			bladeSpan: "142cm",
			reversableBlades: "No",
			controlMethod: "2x2 Surface Mounted Regulator",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "5 Speed",
			motorWattage: "50w",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/661-400x400.jpg",
		},
		{
			itemCode: 662,
			brand: "Decor",
			fanName: "Ozone",
			material: "Aluminium And ABS Plastic",
			bladeCount: "4",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "Yes",
			lightKit: "78mm R7S Globe 80W Max",
			recommendedGlobe: "LED R7S Globe",
			speed: "3 speed",
			motorWattage: "85W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/662-400x400.jpg",
		},

		{
			itemCode: 731,
			brand: "Solent",
			fanName: "High Breeze 80",
			material: "Aluminium",
			bladeCount: "4",
			bladeMaterial: "Aluminium",
			bladeSpan: "120cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "Not Included",
			recommendedGlobe: "None",
			speed: "4 Speed",
			motorWattage: "75W",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/731-400x400.jpg",
		},
		{
			itemCode: 734,
			brand: "Solent",
			fanName: "High Breeze 80",
			material: "Aluminium And Marine Plywood",
			bladeCount: "4",
			bladeMaterial: "Marine Plywood",
			bladeSpan: "120cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "Not Included",
			recommendedGlobe: "None",
			speed: "4 Speed",
			motorWattage: "75W",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/734-400x400.jpg",
		},
		{
			itemCode: 3301,
			brand: "Solent",
			fanName: "High Breeze 80",
			material: "Aluminium",
			bladeCount: "4",
			bladeMaterial: "Aluminium",
			bladeSpan: "120cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "Not Included",
			recommendedGlobe: "None",
			speed: "4 Speed",
			motorWattage: "75W",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/3301-400x400.jpg",
		},
		{
			itemCode: 5813,
			brand: "Decor",
			fanName: "Industrial Fan",
			material: "Steel",
			bladeCount: "3",
			bladeMaterial: "Steel",
			bladeSpan: "142cm",
			reversableBlades: "No",
			controlMethod: "2x2 Surface Mounted Regulator",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "5 Speed",
			motorWattage: "50w",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/5813-400x400.jpg",
		},
		{
			itemCode: 6420,
			brand: "Decor",
			fanName: "Industrial Fan",
			material: "Steel",
			bladeCount: "3",
			bladeMaterial: "Steel",
			bladeSpan: "142cm",
			reversableBlades: "No",
			controlMethod: "2x2 Surface Mounted Regulator",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "5 Speed",
			motorWattage: "50w",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/6420-400x400.jpg",
		},
		{
			itemCode: 6852,
			brand: "Solent",
			fanName: "Senorita",
			material: "Aluminium And Marine Plywood",
			bladeCount: "3",
			bladeMaterial: "Marine Plywood",
			bladeSpan: "120cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "Not Included",
			recommendedGlobe: "None",
			speed: "4 Speed",
			motorWattage: "80W",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/6852-400x400.jpg",
		},
		{
			itemCode: 7180,
			brand: "Decor",
			fanName: "Petit Star Satin Brass",
			material: "Aluminium and MBF wood",
			bladeCount: "6",
			bladeMaterial: "Plywood",
			bladeSpan: "77cm",
			reversableBlades: "No",
			controlMethod: "Pull Switch",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "1 x 60W e27",
			recommendedGlobe: "Golfball",
			speed: "3 Speed",
			motorWattage: "55W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/7180-400x400.jpg",
		},
		{
			itemCode: 12566,
			brand: "Decor",
			fanName: "Celano",
			material: "Steel And Plywood",
			bladeCount: "5",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "Yes",
			controlMethod: "Pull Switch",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "1 x 60W e27",
			recommendedGlobe: "Golfball",
			speed: "3 Speed",
			motorWattage: "60W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/12566-400x400.jpg",
		},
		{
			itemCode: 12567,
			brand: "Decor",
			fanName: "Celano",
			material: "Steel And Plywood",
			bladeCount: "5",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "Yes",
			controlMethod: "Pull Switch",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "1 x 60W e27",
			recommendedGlobe: "Golfball",
			speed: "3 Speed",
			motorWattage: "60W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/12567-400x400.jpg",
		},
		{
			itemCode: 12952,
			brand: "Decor",
			fanName: "Baroque",
			material: "Steel And Plywood",
			bladeCount: "5",
			bladeMaterial: "Plywood",
			bladeSpan: "107cm",
			reversableBlades: "No",
			controlMethod: "Pull Switch",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "1 x 60W e27",
			recommendedGlobe: "Golfball",
			speed: "3 Speed",
			motorWattage: "60W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/12952-400x400.jpg",
		},
		{
			itemCode: 13219,
			brand: "The Lighting Warehouse",
			fanName: "Fleet",
			material: "Steel And Stainless Steel",
			bladeCount: "5",
			bladeMaterial: "Stainless Steel",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 Speed",
			motorWattage: "70W",
			warranty: "2 Year",
			coastal: "No",
			imageLocation: "/assets/images/13219-400x400.jpg",
		},
		{
			itemCode: 14535,
			brand: "Decor",
			fanName: "Baroque",
			material: "Steel And Plywood",
			bladeCount: "5",
			bladeMaterial: "Plywood",
			bladeSpan: "107cm",
			reversableBlades: "No",
			controlMethod: "Pull Switch",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "1 x 60W e27",
			recommendedGlobe: "Golfball",
			speed: "3 Speed",
			motorWattage: "60W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/14535-400x400.jpg",
		},
		{
			itemCode: 14665,
			brand: "Decor",
			fanName: "Galactica",
			material: "Steel",
			bladeCount: "3",
			bladeMaterial: "Steel",
			bladeSpan: "142cm",
			reversableBlades: "No",
			controlMethod: "2x2 Surface Mounted Regulator",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "75W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/14665-400x400.jpg",
		},
		{
			itemCode: 15086,
			brand: "The Lighting Warehouse",
			fanName: "AustralisX",
			material: "Steel And Solid Wood",
			bladeCount: "3",
			bladeMaterial: "Solid Wood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15086-400x400.jpg",
		},
		{
			itemCode: 15092,
			brand: "The Lighting Warehouse",
			fanName: "Scout",
			material: "Steel And Plywood",
			bladeCount: "5",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "75W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15092-400x400.jpg",
		},
		{
			itemCode: 15093,
			brand: "The Lighting Warehouse",
			fanName: "Phoenix",
			material: "Steel And Plywood",
			bladeCount: "3",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15093-400x400.jpg",
		},
		{
			itemCode: 15094,
			brand: "The Lighting Warehouse",
			fanName: "Phoenix",
			material: "Steel And Plywood",
			bladeCount: "3",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15094-400x400.jpg",
		},
		{
			itemCode: 15095,
			brand: "The Lighting Warehouse",
			fanName: "Phoenix",
			material: "Steel And Plywood",
			bladeCount: "3",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15095-400x400.jpg",
		},
		{
			itemCode: 15096,
			brand: "The Lighting Warehouse",
			fanName: "Swift",
			material: "Steel And Plywood",
			bladeCount: "4",
			bladeMaterial: "Plywood",
			bladeSpan: "122cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15096-400x400.jpg",
		},
		{
			itemCode: 15097,
			brand: "The Lighting Warehouse",
			fanName: "Swift",
			material: "Steel And Plywood",
			bladeCount: "4",
			bladeMaterial: "Plywood",
			bladeSpan: "122cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15097-400x400.jpg",
		},
		{
			itemCode: 15098,
			brand: "The Lighting Warehouse",
			fanName: "Swift",
			material: "Steel And Plywood",
			bladeCount: "4",
			bladeMaterial: "Plywood",
			bladeSpan: "122cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15098-400x400.jpg",
		},
		{
			itemCode: 15099,
			brand: "The Lighting Warehouse",
			fanName: "Mistral",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "Yes",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "5 speed",
			motorWattage: "38W DC",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15099-400x400.jpg",
		},
		{
			itemCode: 15100,
			brand: "The Lighting Warehouse",
			fanName: "Mistral",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "Yes",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "5 speed",
			motorWattage: "38W DC",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15100-400x400.jpg",
		},
		{
			itemCode: 15101,
			brand: "The Lighting Warehouse",
			fanName: "Avia",
			material: "Steel And ABS Plastic",
			bladeCount: "5",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "122cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "65W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15101-400x400.jpg",
		},
		{
			itemCode: 15102,
			brand: "The Lighting Warehouse",
			fanName: "Avia",
			material: "Steel And ABS Plastic",
			bladeCount: "5",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "122cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "65W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15102-400x400.jpg",
		},
		{
			itemCode: 15103,
			brand: "The Lighting Warehouse",
			fanName: "Aquarius",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "127cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "60W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15103-400x400.jpg",
		},
		{
			itemCode: 15104,
			brand: "The Lighting Warehouse",
			fanName: "Aquarius",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "127cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "60W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15104-400x400.jpg",
		},
		{
			itemCode: 15105,
			brand: "The Lighting Warehouse",
			fanName: "AustralisX",
			material: "Steel And Solid Wood",
			bladeCount: "3",
			bladeMaterial: "Solid Wood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15105-300x300.jpg",
		},
		{
			itemCode: 15109,
			brand: "The Lighting Warehouse",
			fanName: "Australis",
			material: "Steel And Solid Wood",
			bladeCount: "3",
			bladeMaterial: "Solid Wood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "65W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15109-400x400.jpg",
		},
		{
			itemCode: 15110,
			brand: "The Lighting Warehouse",
			fanName: "Seafarer",
			material: "Steel And Solid Wood",
			bladeCount: "3",
			bladeMaterial: "Solid Wood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "60W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15110-400x400.jpg",
		},
		{
			itemCode: 15113,
			brand: "The Lighting Warehouse",
			fanName: "OhThree",
			material: "Steel And Solid Wood",
			bladeCount: "4",
			bladeMaterial: "Solid Wood",
			bladeSpan: "122cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15113-400x400.jpg",
		},
		{
			itemCode: 15114,
			brand: "The Lighting Warehouse",
			fanName: "Scout",
			material: "Steel And Plywood",
			bladeCount: "5",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "75W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15114-400x400.jpg",
		},
		{
			itemCode: 15115,
			brand: "The Lighting Warehouse",
			fanName: "Capital",
			material: "Steel And Plywood",
			bladeCount: "5",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "65W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15115-400x400.jpg",
		},
		{
			itemCode: 15116,
			brand: "The Lighting Warehouse",
			fanName: "Capital",
			material: "Steel And Plywood",
			bladeCount: "5",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "65W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15116-400x400.jpg",
		},
		{
			itemCode: 15117,
			brand: "The Lighting Warehouse",
			fanName: "Capital",
			material: "Steel And Plywood",
			bladeCount: "5",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "65W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15117-400x400.jpg",
		},
		{
			itemCode: 15118,
			brand: "The Lighting Warehouse",
			fanName: "Breeze",
			material: "Steel And Plywood",
			bladeCount: "4",
			bladeMaterial: "Plywood",
			bladeSpan: "122cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15118-400x400.jpg",
		},

		{
			itemCode: 15119,
			brand: "The Lighting Warehouse",
			fanName: "Breeze",
			material: "Steel And Plywood",
			bladeCount: "4",
			bladeMaterial: "Plywood",
			bladeSpan: "122cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15119-300x300.jpg",
		},

		{
			itemCode: 15121,
			brand: "The Lighting Warehouse",
			fanName: "Breeze",
			material: "Steel And Plywood",
			bladeCount: "4",
			bladeMaterial: "Plywood",
			bladeSpan: "122cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15121-300x300.jpg",
		},
		{
			itemCode: 15122,
			brand: "The Lighting Warehouse",
			fanName: "Whisper",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15122-400x400.jpg",
		},
		{
			itemCode: 15124,
			brand: "The Lighting Warehouse",
			fanName: "Breathe",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "65W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15124-400x400.jpg",
		},
		{
			itemCode: 15125,
			brand: "The Lighting Warehouse",
			fanName: "Wayfarer",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "75W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15125-400x400.jpg",
		},
		{
			itemCode: 15128,
			fanName: "Aquarius",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "127cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "65W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15128-400x400.jpg",
		},
		{
			itemCode: 15338,
			fanName: "Aquarius",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "127cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "65W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15338-400x400.jpg",
		},
		{
			itemCode: 15401,
			brand: "The Lighting Warehouse",
			fanName: "Beachcraft",
			material: "Steel And Solid Wood",
			bladeCount: "3",
			bladeMaterial: "Solid Wood",
			bladeSpan: "122cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "15W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "50W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15401-400x400.jpg",
		},
		{
			itemCode: 15402,
			brand: "The Lighting Warehouse",
			fanName: "Mistral",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "Yes",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "5 speed",
			motorWattage: "38W DC",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15402-400x400.jpg",
		},
		{
			itemCode: 15403,
			brand: "The Lighting Warehouse",
			fanName: "Mistral",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "Yes",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "5 speed",
			motorWattage: "38W DC",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/15403-400x400.jpg",
		},
		{
			itemCode: 15694,
			brand: "Decor",
			fanName: "Wall Fan",
			material: "Steel",
			bladeCount: "4",
			bladeMaterial: "Steel",
			bladeSpan: "40cm",
			reversableBlades: "No",
			controlMethod: "Pull Switch or Dial Switch",
			rodLength: "No Rod",
			timer: "None",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "70w",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/15694-400x400.jpg",
		},
		{
			itemCode: 15968,
			brand: "Solent",
			fanName: "Whirlwind",
			material: "Aluminium",
			bladeCount: "3",
			bladeMaterial: "Aluminium",
			bladeSpan: "140cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "none",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "4 speed",
			motorWattage: "60w",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/15968-400x400.jpg",
		},
		{
			itemCode: 17655,
			brand: "Solent",
			fanName: "High Breeze 80",
			material: "Aluminium",
			bladeCount: "4",
			bladeMaterial: "Aluminium",
			bladeSpan: "90cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "none",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "4 speed",
			motorWattage: "75w",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/17655-400x400.jpg",
		},
		{
			itemCode: 18350,
			brand: "Solent",
			fanName: "Whirlwind",
			material: "Aluminium",
			bladeCount: "3",
			bladeMaterial: "Aluminium",
			bladeSpan: "120cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "none",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "4 speed",
			motorWattage: "60w",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/18350-400x400.jpg",
		},
		{
			itemCode: 18377,
			brand: "Decor",
			fanName: "Ozone Wood",
			material: "Steel And Plywood",
			bladeCount: "4",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "No",
			reversableMotor: "Yes",
			lightKit: "78mm R7S Globe 80W Max",
			recommendedGlobe: "LED R7S Globe",
			speed: "3 speed",
			motorWattage: "60w",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/18377-400x400.jpg",
		},
		{
			itemCode: 18452,
			brand: "Solent",
			fanName: "Whirlwind",
			material: "Aluminium",
			bladeCount: "3",
			bladeMaterial: "Aluminium",
			bladeSpan: "120cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "none",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "4 speed",
			motorWattage: "60w",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/18452-400x400.jpg",
		},
		{
			itemCode: 19328,
			brand: "Solent",
			fanName: "Whirlwind",
			material: "Aluminium",
			bladeCount: "3",
			bladeMaterial: "Aluminium",
			bladeSpan: "120cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "none",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "4 speed",
			motorWattage: "60w",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/19328-400x400.jpg",
		},
		{
			itemCode: 20113,
			brand: "Decor",
			fanName: "Icon",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "No",
			lightKit: "2 x 40W e14",
			recommendedGlobe: "LED Candle Globe",
			speed: "3 speed",
			motorWattage: "65W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/20113-400x400.jpg",
		},
		{
			itemCode: 24384,
			brand: "Solent",
			fanName: "Wall Fan",
			material: "Aluminium And ABS Plastic",
			bladeCount: "4",
			bladeMaterial: "Aluminium",
			bladeSpan: "45cm",
			reversableBlades: "No",
			controlMethod: "Electronic Switch",
			rodLength: "None",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "8 speed",
			motorWattage: "52W DC",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/24384-400x400.jpg",
		},
		{
			itemCode: 24688,
			brand: "Solent",
			fanName: "Whirlwind",
			material: "Aluminium",
			bladeCount: "3",
			bladeMaterial: "Aluminium",
			bladeSpan: "90cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "none",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "4 speed",
			motorWattage: "60w",
			warranty: "2 Years",
			coastal: "Yes",
			imageLocation: "/assets/images/24688-400x400.jpg",
		},
		{
			itemCode: 26021,
			brand: "Solent",
			fanName: "Maxima",
			material: "Aluminium And Marine Plywood",
			bladeCount: "3",
			bladeMaterial: "Marine Plywood",
			bladeSpan: "120cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "4 speed",
			motorWattage: "75W",
			warranty: "2 Years",
			coastal: "no",
			imageLocation: "/assets/images/26021-400x400.jpg",
		},
		{
			itemCode: 26022,
			brand: "Solent",
			fanName: "Maxima",
			material: "Aluminium And Marine Plywood",
			bladeCount: "3",
			bladeMaterial: "Marine Plywood",
			bladeSpan: "120cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "4 speed",
			motorWattage: "75W",
			warranty: "2 Years",
			coastal: "no",
			imageLocation: "/assets/images/26022-400x400.jpg",
		},
		{
			itemCode: 26023,
			brand: "Solent",
			fanName: "Maxima",
			material: "Aluminium And Marine Plywood",
			bladeCount: "4",
			bladeMaterial: "Marine Plywood",
			bladeSpan: "140cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "4 speed",
			motorWattage: "75W",
			warranty: "2 Years",
			coastal: "no",
			imageLocation: "/assets/images/26022-400x400.jpg",
		},
		{
			itemCode: 26024,
			brand: "Solent",
			fanName: "Maxima",
			material: "Aluminium And Marine Plywood",
			bladeCount: "4",
			bladeMaterial: "Marine Plywood",
			bladeSpan: "140cm",
			reversableBlades: "No",
			controlMethod: "2x4 Wall Regulator",
			rodLength: "250mm",
			timer: "None",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "4 speed",
			motorWattage: "75W",
			warranty: "2 Years",
			coastal: "no",
			imageLocation: "/assets/images/26022-400x400.jpg",
		},
		{
			itemCode: 26140,
			brand: "The Lighting Warehouse",
			fanName: "Harbour",
			material: "Metal And MDF Wood",
			bladeCount: "3",
			bladeMaterial: "MDF Wood",
			bladeSpan: "122cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "1 x 60W e27",
			recommendedGlobe: "Golfball or LED stick",
			speed: "3 speed",
			motorWattage: "60W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26140-400x400.jpg",
		},
		{
			itemCode: 26141,
			brand: "The Lighting Warehouse",
			fanName: "Pursuit",
			material: "Metal And MDF Wood",
			bladeCount: "5",
			bladeMaterial: "MDF Wood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "1 x 60W e27",
			recommendedGlobe: "Golfball or LED stick",
			speed: "3 speed",
			motorWattage: "60W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26141-400x400.jpg",
		},
		{
			itemCode: 26142,
			brand: "The Lighting Warehouse",
			fanName: "Pursuit",
			material: "Metal And MDF Wood",
			bladeCount: "5",
			bladeMaterial: "MDF Wood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "1 x 60W e27",
			recommendedGlobe: "Golfball or LED stick",
			speed: "3 speed",
			motorWattage: "55W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26141-400x400.jpg",
		},
		{
			itemCode: 26260,
			brand: "Decor",
			fanName: "Ozone Wood",
			material: "Steel And Plywood",
			bladeCount: "4",
			bladeMaterial: "Plywood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "No",
			reversableMotor: "Yes",
			lightKit: "78mm R7S Globe 80W Max",
			recommendedGlobe: "LED R7S Globe",
			speed: "3 speed",
			motorWattage: "60w",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/26260-400x400.jpg",
		},
		{
			itemCode: 26261,
			brand: "Decor",
			fanName: "Icon",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "112cm",
			reversableBlades: "No",
			controlMethod: "2x2 Surface Mounted Regulator",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "No",
			lightKit: "2 x 40W e14",
			recommendedGlobe: "LED Candle Globe",
			speed: "3 speed",
			motorWattage: "50W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/26261-400x400.jpg",
		},
		{
			itemCode: 26262,
			brand: "Decor",
			fanName: "Icon",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "112cm",
			reversableBlades: "No",
			controlMethod: "2x2 Surface Mounted Regulator",
			rodLength: "TBA",
			timer: "None",
			reversableMotor: "No",
			lightKit: "2 x 40W e14",
			recommendedGlobe: "LED Candle Globe",
			speed: "3 speed",
			motorWattage: "50W",
			warranty: "1 Year",
			coastal: "No",
			imageLocation: "/assets/images/26262-400x400.jpg",
		},
		{
			itemCode: 26549,
			brand: "The Lighting Warehouse",
			fanName: "Samson",
			material: "Steel And Solid Wood",
			bladeCount: "3",
			bladeMaterial: "Solid Wood",
			bladeSpan: "152cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "5 speed",
			motorWattage: "50w DC",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26549-400x400.jpg",
		},
		{
			itemCode: 26550,
			brand: "The Lighting Warehouse",
			fanName: "AustralisX",
			material: "Steel And Solid Wood",
			bladeCount: "3",
			bladeMaterial: "Solid Wood",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "Yes",
			lightKit: "15W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "65w",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26550-400x400.jpg",
		},
		{
			itemCode: 26551,
			brand: "The Lighting Warehouse",
			fanName: "Pioneer",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "Yes",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "5 speed",
			motorWattage: "38w DC",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26551-400x400.jpg",
		},
		{
			itemCode: 26552,
			brand: "The Lighting Warehouse",
			fanName: "Flight",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "112cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "Yes",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "5 speed",
			motorWattage: "38W DC",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26552-400x400.jpg",
		},
		{
			itemCode: 26553,
			brand: "The Lighting Warehouse",
			fanName: "Flight",
			material: "Steel And ABS Plastic",
			bladeCount: "3",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "112cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "Yes",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "5 speed",
			motorWattage: "38W DC",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26553-400x400.jpg",
		},
		{
			itemCode: 26554,
			brand: "The Lighting Warehouse",
			fanName: "Phoenix",
			material: "Steel And Plywood",
			bladeCount: "3",
			bladeMaterial: "Plywood",
			bladeSpan: "106cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "50w",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26554-400x400.jpg",
		},
		{
			itemCode: 26555,
			brand: "The Lighting Warehouse",
			fanName: "Phoenix",
			material: "Steel And Plywood",
			bladeCount: "3",
			bladeMaterial: "Plywood",
			bladeSpan: "106cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "50w",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26555-400x400.jpg",
		},
		{
			itemCode: 26556,
			brand: "The Lighting Warehouse",
			fanName: "Phoenix",
			material: "Steel And Plywood",
			bladeCount: "3",
			bladeMaterial: "Plywood",
			bladeSpan: "106cm",
			reversableBlades: "Yes",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "20W LED Light Kit With CTC",
			recommendedGlobe: "LED Panel",
			speed: "3 speed",
			motorWattage: "50w",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26556-400x400.jpg",
		},
		{
			itemCode: 26557,
			brand: "The Lighting Warehouse",
			fanName: "Umhlali",
			material: "Steel And ABS Plastic",
			bladeCount: "5",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "132cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "85W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26557-400x400.jpg",
		},
		{
			itemCode: 26558,
			brand: "The Lighting Warehouse",
			fanName: "Umdloti",
			material: "Steel And ABS Plastic",
			bladeCount: "5",
			bladeMaterial: "ABS Plastic",
			bladeSpan: "137cm",
			reversableBlades: "No",
			controlMethod: "Remote Control",
			rodLength: "TBA",
			timer: "Yes",
			reversableMotor: "No",
			lightKit: "None",
			recommendedGlobe: "None",
			speed: "3 speed",
			motorWattage: "73W",
			warranty: "2 Years",
			coastal: "No",
			imageLocation: "/assets/images/26558-400x400.jpg",
		},
	];

	const filterFansAccordingToBrand = (brand, arr) => {
		return arr.filter((fan) => {
			return fan.brand === brand;
		});
	};

	const mapFans = (arr) => {
		return arr.map((fan) => {
			return (
				<Fan
					fanName={fan.fanName}
					imageLocation={fan.imageLocation}
					itemCode={fan.itemCode}
					brand={fan.brand}
					material={fan.material}
					bladeCount={fan.bladeCount}
					bladeMaterial={fan.bladeMaterial}
					reversableBlades={fan.reversableBlades}
					bladeSpan={fan.bladeSpan}
					controlMethod={fan.controlMethod}
					lightKit={fan.lightKit}
					recommendedGlobe={fan.recommendedGlobe}
					reversableMotor={fan.reversableMotor}
					rodLength={fan.rodLength}
					warranty={fan.warranty}
					timer={fan.timer}
					coastal={fan.coastal}
					speed={fan.speed}
					motorWattage={fan.motorWattage}
					key={fan.itemCode}
				/>
			);
		});
	};

	const decorFans = filterFansAccordingToBrand("Decor", fans);
	const decorFansMapped = mapFans(decorFans);
	const solentFans = filterFansAccordingToBrand("Solent", fans);
	const solentFansMapped = mapFans(solentFans);
	const tlwFans = filterFansAccordingToBrand("The Lighting Warehouse", fans);
	const tlwFansMapped = mapFans(tlwFans);

	return (
		<main className="bg-white/30">
			<section>
      <div className="container px-6 m-auto h-52 sm:h-64">
					<div className="grid grid-cols-4 gap-6 md:grid-cols-8 lg:grid-cols-12 mt-24">
						<div className="col-span-4 md:col-span-8 lg:col-span-12">
							<Image
								src="/assets/logos/LogoTill-72dpi.jpg"
								width={200}
								height={200}
								alt="TLW"
								className="mx-auto"
							/>
						</div>
					</div>
				</div>
			</section>

			<section>
				<div className="container px-6 m-auto ">
					<div className="grid grid-cols-4 gap-6 md:grid-cols-8 lg:grid-cols-12">
						{tlwFansMapped}
					</div>
				</div>
			</section>

			<section>
				<div className="container px-6 m-auto h-52 sm:h-52">
					<div className="grid grid-cols-4 gap-6 md:grid-cols-8 lg:grid-cols-12 mt-24">
						<div className="col-span-4 md:col-span-8 lg:col-span-12">
							<Image
								src="/assets/logos/solent_logo.png"
								width={300}
								height={300}
								alt="solent"
								className="mx-auto"
							/>
						</div>
					</div>
				</div>
			</section>

			<section>
				<div className="container px-6 m-auto ">
					<div className="grid grid-cols-4 gap-6 md:grid-cols-8 lg:grid-cols-12">
						{solentFansMapped}
					</div>
				</div>
			</section>

			<section>
      <div className="container px-6 m-auto h-52 sm:h-52">
					<div className="grid grid-cols-4 gap-6 md:grid-cols-8 lg:grid-cols-12 mt-24">
						<div className="col-span-4 md:col-span-8 lg:col-span-12">
							<Image
								src="/assets/logos/Decor-Centre-Logo-1.jpg"
								width={200}
								height={200}
								alt="decor"
								className="mx-auto"
							/>
						</div>
					</div>
				</div>
			</section>

			<section>
				<div className="container px-6 m-auto ">
					<div className="grid grid-cols-4 gap-6 md:grid-cols-8 lg:grid-cols-12">
						{decorFansMapped}
					</div>
				</div>
			</section>
		</main>
	);
};

export default Home;
